source:
  third_party_source:
    filepath_regex: [".*/ios/Frameworks/.*", ".*/android/src/main/java/com/tencent/cloud/tts/plugin/tts_plugin/TtsPlugin.java", ".*/example/android/app/src/main/java/com/tencent/cloud/tts/plugin/tts_plugin_example/MainActivity.java"]